// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementApp.Data;

#nullable disable

namespace StudentManagementApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementApp.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "A",
                            Section = "Mathematics",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "B",
                            Section = "Physics",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "A",
                            Section = "Computer Science",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "B",
                            Section = "Mathematics",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "A",
                            Section = "English Language",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "C",
                            Section = "Biology",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "A",
                            Section = "Mathematics",
                            StudentId = 3
                        },
                        new
                        {
                            GradeId = 8,
                            GradeName = "B",
                            Section = "Chemistry",
                            StudentId = 3
                        },
                        new
                        {
                            GradeId = 9,
                            GradeName = "A",
                            Section = "Physics",
                            StudentId = 3
                        },
                        new
                        {
                            GradeId = 10,
                            GradeName = "B",
                            Section = "History",
                            StudentId = 4
                        },
                        new
                        {
                            GradeId = 11,
                            GradeName = "A",
                            Section = "English Language",
                            StudentId = 4
                        },
                        new
                        {
                            GradeId = 12,
                            GradeName = "B",
                            Section = "Physical Education",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("StudentManagementApp.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(2006, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.76m,
                            StudentName = "Alex Johnson",
                            Weight = 68.5f
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(2007, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.65m,
                            StudentName = "Emily Carter",
                            Weight = 54.3f
                        },
                        new
                        {
                            StudentID = 3,
                            DateOfBirth = new DateTime(2006, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.80m,
                            StudentName = "Liam Miller",
                            Weight = 74.2f
                        },
                        new
                        {
                            StudentID = 4,
                            DateOfBirth = new DateTime(2007, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 1.70m,
                            StudentName = "Sophia Brown",
                            Weight = 59.8f
                        });
                });

            modelBuilder.Entity("StudentManagementApp.Models.Grade", b =>
                {
                    b.HasOne("StudentManagementApp.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApp.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
